# Generated by Django 4.0 on 2021-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=2083)),
                ('location', models.CharField(max_length=255)),
                ('who_can_friend_me', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('languages_known', models.CharField(max_length=255)),
            ],
        ),
    ]
