# Generated by Django 4.0 on 2021-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dog_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
