# Generated by Django 4.0 on 2021-12-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dog_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='age',
            new_name='dob',
        ),
    ]
